theme: jekyll-theme-merlot
lugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - test2.md

title: <Brittany's Website>
description:Hello! Welcome to my website.
