theme: jekyll-theme-merlot
lugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - <About me>.md

title: <Brittany's Website>
description:< Hello! Welcome to my website.> 
